platform :ios, '9.0'
workspace '../GApp'

target 'GOne' do
  use_frameworks!

  pod 'SwiftyJSON', '~> 2.3'
  pod 'AFNetworking', '~> 3.0'

  target 'GOneTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GOneUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
